all:
	g++ -c -g -L/home/x000ff4/Свалени/mysql-connector-c++-1.0.5-linux-glibc2.3-ia64-64bit/lib/ -I /home/x000ff4/Свалени/mysql-connector-c++-1.0.5-linux-glibc2.3-ia64-64bit/include/ simpleSQL.cpp
	-l:libmysqlcppconn.so.7  
clean:
	rm simpleSQL.o
