all: CommandAndControll VirtTableHolder
CommandAndControll:
	c++ CommandAndControll.cpp -I/home/x000ff4/Свалени/rapidjson-master/include/ -std=c++11 -c
VirtTableHolder:
	c++ VirtTableHolder.cpp -std=c++11 -c
clean:
	$(RM) CommandAndControll.o VirtTableHolder.o
