all: CommandAndControll VirtTableHolder
CommandAndControll:
	c++ -w CommandAndControll.cpp  -std=c++11 -c
VirtTableHolder:
	c++ VirtTableHolder.cpp -std=c++11 -c
clean:
	$(RM) CommandAndControll.o VirtTableHolder.o
