all: CommandAndControll VirtTableHolder
CommandAndControll:
	c++ -I "/home/x000ff4/Свалени/rapidjson-master/include" -w CommandAndControll.cpp  -std=c++11 -c
VirtTableHolder:
	c++  VirtTableHolder.cpp -std=c++11 -c
clean:
	$(RM) CommandAndControll.o VirtTableHolder.o
